apiVersion: v1
data:
  OPENSHIFT_ACTIVEMQ_PASSWORD: clQ0ZFp4MDlpVlhxNDJY
  OPENSHIFT_ACTIVEMQ_USER: YW1xLXVzZXI=
kind: Secret
metadata:
  creationTimestamp: '2019-08-15T21:23:48Z'
  name: maind-dispatch-secrets
  namespace: citinova-logincidadao-dev
  resourceVersion: '36579233'
  selfLink: /api/v1/namespaces/citinova-logincidadao-dev/secrets/maind-dispatch-secrets
  uid: f85f1260-bfa2-11e9-9f65-005056b5c3ef
type: Opaque
