apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2019-08-09T17:10:53Z'
  labels:
    app: main-dispatch-gateway
  name: main-dispatch-gateway
  namespace: citinova-logincidadao-dev
  resourceVersion: '33381452'
  selfLink: /api/v1/namespaces/citinova-logincidadao-dev/services/main-dispatch-gateway
  uid: a4e370b7-bac8-11e9-b9ef-005056b5c3ef
spec:
  clusterIP: 10.204.181.91
  ports:
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    - name: 9779-tcp
      port: 9779
      protocol: TCP
      targetPort: 9779
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: main-dispatch-gateway
    deploymentconfig: main-dispatch-gateway
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
